# This file defines parameters specific to the Maelstrom ROV
#
# When looking at the ROV from above, the thruster placement is:
#  ___    ___
# |   |__|   |
# |F1      F2|    N
# |    F5    |    ^
# |          | W<-|->E
# |    F6    |    v
# |F4      F3|    S
# |__________|
#   REAR END
#
# Using the compass shown:
# F1 is positive NE
# F2 is positive NW
# F3 is positive SW
# F4 is positive SE
# F5 is positive down
# F6 is positive down

physical:
  mass_kg: 15.0
  displacement_m3: 0.015
  center_of_mass: [0, 0, -0.15]
  center_of_buoyancy: [0, 0,  0.10]
  inertia: [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
           [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
           [0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
           [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
           [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
           [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]]
  added_mass: [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
              [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
              [0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
              [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
              [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
              [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]]
  linear_damping: [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                   [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
                   [0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
                   [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
                   [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
                   [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]]
# quad damping: Xuu Yvv Yrv Yvr Yrr Zww Kpp Mqq Nvv Nrv Nvr Nrr
# Initialised with only diagonal elements in matrix
  quad_damping_vector: [1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0]

rov:
  euler_initial: [0.0, 0.0, 0.0]
  position_initial: [0.0, 0.0, 0.0]

propulsion:
  thrusters:
    num: 6
    configuration_matrix:
      [[ 0.7071,  0.7071, -0.7071, -0.7071,     0.0,    0.0], # Surge
       [ 0.7071, -0.7071, -0.7071,  0.7071,     0.0,    0.0], # Sway
       [    0.0,     0.0,     0.0,     0.0,     1.0,    1.0], # Heave
       [-0.0467, -0.0467,  0.0467,  0.0467, -0.1600, 0.1600], # Pitch
       [ 0.2143, -0.2143,  0.2143, -0.2143,     0.0,    0.0]] # Yaw



